### ISSUE TITLE
Requesting a relative path (in browser)

### ISSUE THREAD

**Issue by lukehorvat** [sindresorhus/got#87]
I am using `got` in the browser via Browserify. The URL of my web app is `http://localhost:8000/app/#/`. I'd like to send a GET request to `http://localhost:8000/app/ping`.

With [`xhr`](https://github.com/Raynos/xhr), one can specify the request URL as `./ping`, and it works. I quite like this because then I don't need to worry about the hostname and whatnot. But with `got`, it seems to make the request to `http://./ping`.

Just wondering if we could mimic `xhr`'s functionality in this instance?

**Comment by sindresorhus** [comment]
Yeah, that seems like a bug in https://github.com/sindresorhus/prepend-http Will fix.

I didn't realize `got` works in the browser through `browserify`. That's awesome! I assume browserify shims the `http` module using XHR.

**Comment by arthurvr** [comment]
> I didn't realize got works in the browser through browserify.

I didn't eighter. Super cool! If we can confirm everything works fine I'd even say that's a welcome addition to the readme?

**Comment by sindresorhus** [comment]
Definitely!

**Comment by kevva** [comment]
@sindresorhus, they recently added better support for streams too for browsers that supports it. https://github.com/substack/node-browserify/blob/master/changelog.markdown#1100.

**Comment by sindresorhus** [comment]
@lukehorvat Should be fixed now. Try reinstalling `got` ;)

**Comment by floatdrop** [comment]
This is relevant to - https://github.com/mdlavin/nested-error-stacks/pull/6

**Comment by lukehorvat** [comment]
Thank you @sindresorhus. :dancer:

**Comment by lukehorvat** [comment]
Just having a play around with it now. It seems to send the request to `http://localhost:8000./status`, which still isn't correct, but is close. It looks like [`http-browserify`](https://github.com/substack/http-browserify) is the cause of the problem this time, so I will open an issue in that repo.

**Comment by sindresorhus** [comment]
@lukehorvat Alright, paste in the link to the issue when you do so we can follow along.

**Comment by lukehorvat** [comment]
@sindresorhus Okay, I've opened an issue [here](https://github.com/substack/http-browserify/issues/92) with an accompanying PR. Unfortunately there are 31 other pending PRs so I don't think it's going to get merged any time soon. :neutral_face:

**Comment by bendrucker** [comment]
http-browserify was replaced by https://github.com/jhiesey/stream-http in browserify@11

**Comment by bendrucker** [comment]
Also I'm gonna bring in @floatdrop's captureStackTrace ponyfill to nested-error-stacks in mdlavin/nested-error-stacks#6 instead of the naive initial solution I proposed. Right now got's not really compatible with browserify (b/c nested-error-stacks isn't). It'll work in Chrome, but any errors will result in an exception in a non-V8 browser (IE, Safari, Firefox).

**Comment by lukehorvat** [comment]
Happy to report that as of `stream-http` v1.6.0, relative paths work when using `got` in the browser. :muscle:
